version: "3.7"

services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=FlaskTest
        expose:
            - 5000

    nginx:
        build: ./frontend
        container_name: nginx
        restart: always
        ports:
            - "8090:8090"
        volumes:
            - type: bind
            source: /mnt/c/nginx-cache
            target: /nginx-cache